import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BlogHeader as Header } from "@/components/layout/Header";
import { BlogFooter as Footer } from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface ContainerProps {
  children: React.ReactNode;
  maxWidth?: "sm" | "md" | "lg" | "xl" | "2xl";
}

const MAX_WIDTH_CLASSES = {
  sm: "max-w-md",
  md: "max-w-lg",
  lg: "max-w-xl",
  xl: "max-w-2xl",
  "2xl": "max-w-2xl",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-background`}
      >
        <div className="flex-1">
          <div className={`${MAX_WIDTH_CLASSES["2xl"]} mx-auto px-6 py-12`}>
            <Header />
            <main>{children}</main>
          </div>
        </div>

        <div
          className={`w-full ${MAX_WIDTH_CLASSES["2xl"]} mx-auto px-6 pb-12`}
        >
          <Footer />
        </div>
      </body>
    </html>
  );
}
